name: Test
on: [workflow_call, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
